### ISSUE TITLE
Parameter resolvers may be of interest

### ISSUE THREAD

**Issue by drewburlingame** [ArdourTech/habitat-cli#3]
Hi, I'm one of the maintainers of CommandDotNet.  Every now and then I look through the list of repos using our package to see how it's being used.  I want to say that I'm delighted by how well you've adopted the features of the framework.  It's one of the most elegant utilizations I've seen so far.  

I hope I'm not overstepping by suggesting a feature that I think you may find useful.  I liked your [PoorManDependencyInjection](https://github.com/ArdourTech/habitat-cli/blob/master/Habitat.Cli/Program.cs#L18).  I noticed that results in the ServiceLocator pattern by querying the Services collection within each command.  Are you aware of [Parameter Resolvers](https://commanddotnet.bilal-fazlani.com/extensibility/parameter-resolvers/).  With them define IDocker as a parameter of the command.

```c#
        public async Task<int> RunAsync(CommandContext context, BuildArgs args)
        {
            var docker = context.Services.GetOrThrow<IDocker>();
```

becomes 

```c#
        public async Task<int> RunAsync(IDocker docker, BuildArgs args)
        {
```

Just add `appRunner.Configure(b => b.UseParameterResolver(ctx => ctx.Services.Get<IDocker>()))`  or `appRunner.Configure(b => b.UseParameterResolver(ctx => new Docker(ctx.CancellationToken)))` and remove the BasicDependencyInjection method.  If you use the latter with the CancellationToken, don't forget to `appRunner.UseCancellationHandlers()`.

Again, nice work.  Hit me up on the discussions panel in our repo if you have any questions.

Cheers, Drew.

**Comment by axrs** [comment]
@drewburlingame Thanks for the insight. I was looking at the Parameter resolver thinking they could help simplify a few things. I'll definitely take it on board and improve the implementation. I looked into the Dependency Injection implementations (which I will need in the future), but I will need to spend some time playing with the frameworks first. 

> I want to say that I'm delighted by how well you've adopted the features of the framework.

I have only been able to get as far as I have because of the provided documentation. It took me a while to comb through it, but once I did, I found everything to be straight forward. So a big thanks to you and the other maintainers.

CommandDotNet has been a dream to work with so far. It's ticking all the boxes I've been looking for:
* Top Notch help docs
* Cross Platform support (thanks to .NET Core 5.0)
* Higher Level Language with better tooling support than say bash
* Fast execution time (much faster than Java)
* Automatic Help Docs with ease of configuration, prompt of arguments, and automatic Environment Variable adaptions

I'm looking forward to modernizing more of my project automation scripts with CommandDotNet.

> It's one of the most elegant utilizations I've seen so far.

Thanks! Hopefully my implementation will evolve more and I'll get to experience more that CommandDotNet has to offer.

**Comment by drewburlingame** [comment]
I'm glad it's been a dream to work with.  I feel the same.  It makes me happy every time I build a new console app.  If you have any suggestions on how the documentation or ramp-up time could be improved, please feel free to suggest them.
